<?php 


#THE MIGRATION FOLDER IS TO WRITE YOUR SQL COMMAND SO WE CAN RUN IT LOCALLY RATHER THAN SENDING  DATABASES.

#CREATE SEVERAL SQL FOR DIFFERENT TABLES, ON MODIFICATION, YOU COULD MODIFY AN ALREADING EXISTING SQL 

?>
